//import  v4 as uuidv4 } from 'uuid';

export const STACKLIST = [
  "Node.js", 
  "Python",
  "Php",
  "PostgreSQL", 
  "Java", 
  "Elasticsearch",
  "MySQL",
  "Symphony",
  "MongoDB",
  "Redis",
  "Django",
  "Ruby",
  "Ruby on Rails",
  "React.js",
  "JavaScript", 
  "Vue.js",
  "TypeScript", 
  "HTML5", 
  "Angular", 
  "CSS3", 
  "SASS", 
  "Redux.js",
  "Angular.js",
  "Docker", 
  "AWS",
  "Kubernetes",
  "GitLab", 
  "Ansible", 
  "GitHub", 
  "Git", 
  "Google Cloud Platform",
  "Terraform", 
  "Azur",
  "Python(dataScience)",
  "Graphana", 
  "Apache Spark", 
  "Google Analytics", 
  "Kibana", 
  "Hadoop",
  "Tableau", 
  "TensorFlow", 
  "Google BigQuery", 
  "R", 
  "React Native", 
  "Kotelin (Android)", 
  "Java (Android)",
  "Objective-C(IOS)", 
  "Ionic", 
  "Apache Cordova",
  "Flutter", 
  "Android SDK", 
  "PWA", 
  "Swift(IOS)",
  "Slack", 
  "Trello", 
  "Confluence", 
  "Notion.so",
  "Asana", 
  "InVision",
  "Microsoft Teams",
  "Google Drive",
  "RedMine", 
  "GitHub Issues",
  "Jira", 
  "Visual Studio Code",
  "Intelligy", 
  "Sublime Text", 
  "Atom",
  "Vim",
  "Eclipse", 
  "Android Studio",
  "Xcode", 
  "PHP Storm",
  "WebFlow",
  "Joomla",
  "Wix", 
  "SquareSpace",
  "Drupal", 
  "Bitrix", 
  "Blogger",
  "Strapi",
  "Zapier", 
  "Bubble",
  "Magento",
  "Integromat",
  "AirTable",
  "Umso",
  "Adalo",
  "Glide",
  "Clickup", 
  "WordPress"
];
